### ISSUE TITLE
dynamo-notebooks/NASC_seq/NASC_seq_analysis.ipynb SparseVFC error

### ISSUE THREAD

**Issue by qinqian** [aristoteleo/dynamo-release#10]
Hello, dynamo team, 

When I am using the latest dynamo to run your jupyter notebook, it output the following errors for the dyn.tl.VectorField function. The notebook seems to be not compatible with the latest dynamo. 

UnboundLocalError: local variable 'P' referenced before assignment.

**Comment by Xiaojieqiu** [comment]
Thanks for using dynamo! I will push a fix in a one hour or two. Thanks

**Comment by qinqian** [comment]
Thanks Xiaojie!

**Comment by Xiaojieqiu** [comment]
Hey @qinqian I made a few changes to dynamo. The vector field learning in the high dimension should work nicely now. 
I think one thing I have to clarify is that the dynamo-notebook repo is not synced with dynamo package right now and  I don't have intention to sync it in the future also (because **I plan to make it the repo for notebooks that will reproduce figures in my final publication**). What on my agenda in the next a few days is however to make a new repo, named **dynamo-tutorials** that will have tutorials on using the latest dynamo to analyze regular scRNA-seq, NASC-seq or scSLAM-seq data.

**Comment by Xiaojieqiu** [comment]
to get you started with dynamo, please check the **dynamo workflow** [section](https://github.com/aristoteleo/dynamo-release#dynamo-workflow). I also include the following scripts which demonstrate on analyzing the **hgForebrainGlut** datasets: 
```from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
%matplotlib inline


import dynamo as dyn 
import anndata
dyn.__version__
```
```
dyn.configuration.set_figure_params('dynamo')  # for beautified visualization
```
```
adata = dyn.sample_data.hgForebrainGlut() 
adata
```
```
dyn.pl.show_fraction(adata)
```
```
adata = dyn.pp.recipe_monocle(adata, n_top_genes=3000)
```
```
dyn.pl.variance_explained(adata)
```
```
dyn.pl.featureGenes(adata)
```
```
import time
start_time = time.time()
tmp=dyn.tl.dynamics(adata)
print("--- %s seconds ---" % (time.time() - start_time))
```
```
dyn.tl.reduceDimension(adata, velocity_key='velocity_S',reduction_method='trimap')
```
```
dyn.tl.cell_velocities(adata, vkey='pca', basis='trimap', method='analytical')
```

```
gene_list=["DCX"]
color = ['stationary_distribution']
dyn.pl.cell_wise_velocity(adata, genes=gene_list, basis='trimap', n_columns=3) # ['GRIA3', 'LINC00982', 'AFF2']

```

```
dyn.pl.grid_velocity(adata, genes=gene_list, basis='trimap', n_columns=2, figsize=[8, 8])  # ['GRIA3', 'LINC00982', 'AFF2']
```
```
dyn.pl.stremline_plot(adata, genes=gene_list,  basis='trimap', n_columns=2, figsize=[8, 8], density=3)  # ['GRIA3', 'LINC00982', 'AFF2'] color=['ClusterName'],
```
```
# show stationary distribution
dyn.tl.stationary_distribution(adata)
```
**# learn vector field and predict long range dynamics in transcriptomic space here**
```
dyn.tools.VectorField(adata, basis='X')
dyn.tl.Fate(adata, query_cell_str='Clusters==0')
```

**Comment by Xiaojieqiu** [comment]
I probably can add this tutorial and others to the new repo in a couple days. But here is a glance of some results on this ** hgForebrainGlut** dataset (the grid velocity / streamline plot): 
<img width="658" alt="Screenshot 2019-11-08 00 58 46" src="https://user-images.githubusercontent.com/7456281/68463202-fa217000-01c2-11ea-8f9e-b169a89305fb.png">

**Comment by qinqian** [comment]
Thank @Xiaojieqiu a lot for the detailed explanation, I'll give it a try and keep you posted about the results.

**Comment by Xiaojieqiu** [comment]
@qinqian we made significant updates to dynamo and now provided detailed analysis for 8 different datasets.  You can check those notebooks here: https://github.com/aristoteleo/dynamo-tutorials

**Comment by qinqian** [comment]
> @qinqian we made significant updates to dynamo and now provided detailed analysis for 8 different datasets. You can check those notebooks here: https://github.com/aristoteleo/dynamo-tutorials

Hi Xiaojie,
 
I tried one of the tutorial notebook (pancreatic_endocrinogenesis.ipynb) with the latest dynamo from github, the version (0.0+59df904) is different from the version (0.0+07100a0) in the notebook, and caused an error at dyn.tl.dynamics(adata, mode='moment'), which raises: 

```
AttributeError: 'tuple' object has no attribute 'nonzero'
```

Is there a newer release somewhere to try? 

Best wishes,
Qian

**Comment by Xiaojieqiu** [comment]
Hi Qin, sorry about this. I am making a bunch changes to the code right now which may break the notebook. For now, in order to reproduce those notebooks, can you install the package from the `07100a0`? 

this can be achieved by running (in the dynamo-release folder)
```
git checkout 07100a0
```
following by `python setup.py install -user `

**Comment by Xiaojieqiu** [comment]
also, make sure numpy / pandas's version satisfies: 
'numpy>=1.18.1', 'pandas>=0.25.1'

**Comment by Xiaojieqiu** [comment]
hi @qinqian just to wanna follow up that I have rerun the notebook last night (with the latest version of dynamo) and found it runs through smoothly. My bet is that the culprit is the numpy / pandas version issue. dynamo is getting stable also, so hopefully I will submit to PyPi in a couple of weeks. I will keep this issue closed but let me know if you have any other questions and you can open a new issue at your will.

**Comment by qinqian** [comment]
Hi @Xiaojieqiu,

Thank you so much for your help! I updated my local codebase of dynamo to lastest master branch, it now works. The results look similar in terms of the trajectory arrows directions, the only difference is the UMAP orientation, perhaps the random seed can be fixed here to fully reproduce the results. 
Here are the final results I got from the pancreatic_endocrinogenesis tutorial ![image](https://user-images.githubusercontent.com/884386/77690089-232b7d00-6f79-11ea-9abc-57fab44a01ff.png)

Thanks again, great works!
Best wishes,
Alvin

**Comment by Xiaojieqiu** [comment]
@qinqian 
just wanna let you know that after 1100 more commits, we have release dynamo on PyPi. I would like to hear some of your comments/suggestions regarding the API before I am going to finalize them. Please let me know if you have any other comments also.
