### ISSUE TITLE
Cell_cycle plot scEU-seq

### ISSUE THREAD

**Issue by Fra-Mante** [aristoteleo/dynamo-release#247]
Hello @Xiaojieqiu,

Last week I run the scEU-seq tutorial script and I noticed that, without changing either virtual environment or input dataset, the cell cycle plot looked significant different when I run the script in different days. Here the plot run on Oct 12:
![12_Oct_1pmUK](https://user-images.githubusercontent.com/64080177/137903838-49124c20-9fe1-42fe-ae96-61f727d4cf33.png)
And here the plot run on Oct 13:
![13_Oct_1pmUK](https://user-images.githubusercontent.com/64080177/137903896-6196bd1e-355b-40ad-86f1-f85da41eec3e.png)
If I run the script today, the plot still looks like as in Oct 13. Either ways, the plot looks more or less different from what is shown on the online tutorial. Do you know the reason why? 
As indicated in previous issue chats, for all the above cases:
- I download the dataset from [here](https://dynamo-release.readthedocs.io/en/latest/scEU_seq_rpe1_analysis_kinetic.html)
- Filtered out 430 genes otherwise the  error `ValueError: looks like your var_names may be corrupted (i.e. include nan values)` was occurring
- Add addition arguments to some f the function, as you indicated. 

Also, as I side question, if I want to run a sensibility test to measure the effect of using less cells for the RNA velocity analysis, which adata parameters should I use?
Thanks

**Comment by Xiaojieqiu** [comment]
@Fra-Mante I Sorry for the delay. The previous issues arise because we overhaul the methods on how we estimate the kinetic parameters a while ago. I have fixed the part related to transition gene selection already. But it will take a little more time for me to figure out the best way to address the issue of RNA velocity flow. We may need to update the notebook largely to use the current estimation strategies
