### ISSUE TITLE
Questions about comparing this tool with CellRank (by Theis lab)

### ISSUE THREAD

**Issue by HelloWorldLTY** [aristoteleo/dynamo-release#268]
Hello, I am a little confused about how to compare these tools. It seems that their functionalities are pretty similar, while CellRank can also estimate cell fate or cell trajectory. However, cellRank need RNA velocity as input.

Will you consider to compare the similar functions between these two tools? Thanks a lot.

**Comment by Xiaojieqiu** [comment]
@HelloWorldLTY thanks for your interests in our work. in our view, dynamo is fundamentally unique from any other existing tools in the sense that we learns the continuous and differentiable function of vector field in transcriptomic space of the single cell kinetics while all others work in the domain of `discrete velocity vectors` (or some discrete time / space  Markov chain based on these velocity vector samples). With the analytical function, we can do many cool things that are entirely new and not possible from others (Figure 1). For example, we can calculate the higher differentials, including RNA Jacobian, acceleration, divergence, curvature, etc, analytically and highly efficiently. Such analyses then result in mechanistic insights of cell fate commitment, like we are able to reveal the minimal network of Meg lineage's early appearance (Figure 2), basophil's dual origins  (See figure 5 in our Cell paper) and even reveal the cooperativity and Hill co-efficient of Pu.1-Gata1 (See figure SI6 in our Cell paper). Furthermore, the continous function make it possible for us to make non-trivial predictions, for example the optimal reprogramming paths and transcription factors (Figure 3) as well as the perturbative outcomes after genetic perturbations (Figure 4). Overall we move from discrete and descriptive analyses of RNA velocity to continous vector field function and predictive and mechanistic models of cell fate transition (Figure 5). 

<img width="1050" alt="Screen Shot 2022-02-01 at 11 31 34 AM" src="https://user-images.githubusercontent.com/7456281/152689118-823ec2cd-9159-42ea-bc3d-77110e3899a6.png">
(Figure 1: dynamo enables dynamical systems and differential geometry analyses)
<img width="1514" alt="Screen Shot 2022-02-01 at 11 32 50 AM" src="https://user-images.githubusercontent.com/7456281/152689152-5cc6a5fe-5375-449c-9af8-540c53893f65.png">
(Figure 2: dynamo reveal regulatory network that explains the early appearance of meg lineage)
<img width="840" alt="Screen Shot 2022-02-06 at 10 54 51 AM" src="https://user-images.githubusercontent.com/7456281/152689264-62392b27-b81a-4cc7-95f7-c133beae8d32.png">
(Figure 3: dynamo predicts the optimal paths and gene sets for reprogramming one cell state to another)
<img width="1374" alt="Screen Shot 2022-02-06 at 10 55 04 AM" src="https://user-images.githubusercontent.com/7456281/152689291-2b59f4b7-afbf-4d90-8dc9-901a560140ce.png">
(Figure 4: dynamo predicts the genetic outcome after genetic perturbations)

![Dynamo](https://user-images.githubusercontent.com/7456281/152110270-7ee1b0ed-1205-495d-9d65-59c7984d2fa2.png)
(Figure 5: what can dynamo do?)

On the part of predicting cell trajectory, since dynamo learns a function, you can use this function just like an ODE (ordinary differential equation) in transcriptomic space to perform integration starting from any intial points -- including `points that are not sampled and measured from the data`, to predict the long term trajectory of single cells. This is similar to what we learned in colleague calculus, you can integrate an ODE given some intitial conditions. We show our prediction match up the clone traced single cells (see Figure 6)
 <img width="1171" alt="Screen Shot 2022-02-06 at 10 41 47 AM" src="https://user-images.githubusercontent.com/7456281/152688726-08da6da5-2718-460a-ba61-f1cc9cd83867.png">
(Figure 6: dynamo predicts long-term trajectories)

Those analyses can be utlized to make simulations of single cell trajectories over time, as you can see here: 

https://user-images.githubusercontent.com/7456281/152688779-07589aed-5b55-4f24-9c6b-747c70c6acfa.mp4
(animation: dynamo can predicts long-term trajectories and create animations of single cell trajectories from any point in the gene expression space)

Importantly, although dynamo can also take the RNA velocity vectors estimated from conventional scRNA-seq data, we made great efforts to also improve the RNA velocity vector estimation by 1). incorporating the new metabolic labeling based scRNA-seq which explicitly label the nascent RNA and thus can better reveal RNA kinetics from the spliced / unspliced RNA that incidentally captured in conventional scRNA-seq data (a byproduct of mis-priming of the intronic region). 2) develop a whole set of estimation methods to deal with different metabolic labeling strategies which can give us absolute RNA velocity (meaning it can tell us how many mRNA will be produced in a particular time period). We show these improve overcome many intrinsic limitations (constant transcription rate assumption, biased capture of unspliced RNA, etc.) from the conventional scRNA-seq, regardless of the tools (including the most sophiscated dynamic model from scVelo) (see Figure 7)  
<img width="1403" alt="Screen Shot 2022-02-01 at 11 26 29 AM" src="https://user-images.githubusercontent.com/7456281/152688997-bc2896d6-7b9a-474f-add0-b76fcdafdabd.png">
(Figure 7: dynamo overcomes intrinsic limitation of convetional scRNA-seq and conventional RNA velocity estimations)

Please note that a preprint released by us since July 2019 (https://www.biorxiv.org/content/10.1101/696724v1.article-metrics), and the paper now is published on Cell. To gain deep understanding of our work, I recommend to go through our [paper](https://www.sciencedirect.com/science/article/pii/S0092867421015774) which can be free accessed (we paid 9000 $ to make it public and facilitate scentific communication).

 If you have further questions / comments, I am happy to discuss with you further. You can even reach out me with my email address xqiu@wi.mit.edu and schedule a 30 min zoom meeting. Thanks and hope this helps

**Comment by HelloWorldLTY** [comment]
Thanks a lot, it really helps me to understand this tool. Cool project!
