### ISSUE TITLE
Merging samples

### ISSUE THREAD

**Issue by DanieleMuraro** [aristoteleo/dynamo-release#280]
Hi,

I was wondering how to merge different samples for the analysis with dynamo.
For a single sample, I am importing the loom file from the velocyto output:

```
adata = dyn.read_loom('velocyto_sample1.loom')
```

Should I use ```loompy.combine``` from velocyto?

https://velocyto.org/velocyto.py/tutorial/cli.html#merging-multiple-samples-lanes-in-a-single-file

Is there any batch correction method available for RNA velocity?

Thanks,

Daniele

**Comment by Xiaojieqiu** [comment]
Dear @DanieleMuraro , thanks for your question. Yes, you shoould use other tools to merge the data. either using loompy.combine or anndata. 

Regarding batch correction, my suggestion is to use other batch correction tools to first correct batch, and then take the umap embedding or other low dimensional embedding to project the velocity to that space. 

Batch correction directly for RNA velocity is a difficult problem because it may destroy the structure of the data (for example, spliced/unspliced layers will have zero which is not meaningful for the velocity estimation.)
