### ISSUE TITLE
Question about rank acceleration

### ISSUE THREAD

**Issue by lh12565** [aristoteleo/dynamo-release#309]
Hi, I have a simple questions about rank acceleration. Is `abs` just changing the sign? If yes, Why is `BIK` ahead of `S100A6` in column 1 of `rank_abs_acceleration` as follows:
```python
adata.uns['rank_abs_acceleration']
           0       1       2       3       4
0        BIK     BIK  TUBA1B  MALAT1   HSPA5
1      HMGB2     FOS   HMGB2     BIK   HMGB2
2     TMSB4X  S100A6    TUBB  TUBA1B  MALAT1
3       RBP1   PRDX1    TYMS    CD24   PTTG1
4       MEST    KLF4   BIRC5   HMGB2   ACTG1
...      ...     ...     ...     ...     ...
1995  CCDC32    ENSA    SIK3    SIK3  GRIN3A
1996   TANC1  POU6F2   RIMS1   CRMP1   HDAC9
1997   INTS6  CCDC32   HDAC9  GRIN3A    IQCG
1998  ADGRV1   HDAC9   PDE4D  CCDC32    RAI1
1999   HDAC9   SRSF1   CRMP1   HDAC9   TANC1

adata.uns['rank_acceleration']
           0       1       2        3       4
0      HMGB2   HMGB2    CD24   MALAT1  MALAT1
1     MALAT1   TOP2A   ASCL1    TOP2A   NEAT1
2      TOP2A    CKS2   BNIP3  C6orf48    MIAT
3       CKS2   DDIT3   RPS18    ZFAS1    CDK1
4     EIF4A2  MALAT1  RPL13A   EIF4A2    SYT1
...      ...     ...     ...      ...     ...
1995   BASP1    CD24    PCNA     RBP1    PTMS
1996    TFF3  TMSB4X    TYMS    PRDX1   UBE2S
1997    MEST    RBP1    TUBB     PCP4   ACTG1
1998    RBP1     BIK   HMGB2   TUBA1B   PTTG1
1999  TMSB4X  S100A6  TUBA1B      BIK   HSPA5
```
Can I get the value used by the rank, as I don't know if it is positive or negative regulation. I found the acceleration stored in `adata.layers['acceleration']`  (cell by gene). Are the `rank acceleration` ranked by the average of the same group?
Please also solve the #304, if you are free. Thanks!

**Comment by Xiaojieqiu** [comment]
Hi @lh12565 I am aware of your issues. Will find sometime later tonight to address them

**Comment by Xiaojieqiu** [comment]
Thanks again for using dynamo. I finally got some time to address your questions: 
1. Is abs just changing the sign? If yes, Why is BIK ahead of S100A6 in column 1 of rank_abs_acceleration as follows:
2. Can I get the value used by the rank, as I don't know if it is positive or negative regulation. 
3.Are the rank acceleration ranked by the average of the same group?

My answers are the following: 
1. yes, the `abs` means that we will first calculate the absolute value of the acceleration (convert negative values to positive values) before we rank genes. This will reveal the magnitute of RNA acceleration while ignore the direction. For your specific question regarding this two genes. I recommend you to plot the acceleration values of this two genes to reveal the acceleration values across cells: `dyn.pl.scatters(adata, layer='acceleration', color=['Tmsb4x', 'Cck'])`
2. yes, you can. Please pass the `output_values = True` to `dyn.vf.rank_acceleration_genes`
3. that is right, if you pass the cell `groups` argument, you will get the ranking for each cell group. Otherwise it will be ranked across all cells. all ranking are based on the average values. 

Btw, I have updated the documentation of the dynamo in my latest commits, please git pull and setup install to see those updates. I will release a new version of dynamo in a few days to pypi. 

Please see my answer to your question in the other github issue

**Comment by lh12565** [comment]
Thanks, I also have a problem of downstream analysis. When I run the code as follows to visualize the bar of group, the bar did not show up:
```python3
dyn.pl.kinetic_heatmap(adata,
                       genes=transition_genes,
                       tkey='pca_ddhodge_potential',
                       gene_order_method='maximum',
                       mode='pseudotime',
                       color_map='viridis',
					   #xticklabels=True, 
                       yticklabels=False, 
		       cell_group='leiden',
		       cell_group_cmap='BrBG')
```
![kinetic_heatmap](https://user-images.githubusercontent.com/24219321/158737702-4d9bdb93-0ca1-4f7f-bff5-997c64ad0d80.png)

**Comment by Xiaojieqiu** [comment]
Dear @lh12565 , I have explained to you `abs` means we use the absolute value for ranking.  Without `abs` it of course uses the raw values and that is why you can see negative values in the resultant ranking table. 
 
regarding to the missing leiden group, that is strange because  `col_colors=col_colors,` has passed to the clustermap function which in theory should plot the plot. Have you tried in a different dataset and tried supplied the argument `cell_group_cmap` with a different color map

@dummyindex could you please also take a look at this issue?

**Comment by dummyindex** [comment]
Sure I will take a look at this color bar issue.
