### ISSUE TITLE
matplotlib 3.5.1 compatibiliy known issue collection

### ISSUE THREAD

**Issue by dummyindex** [aristoteleo/dynamo-release#326]
Our notebooks are tested generally on matplotlib **3.4.3**.

Know issues with matplotlib 3.5.1:
- tight_layout()
- animation

#318 #297

**Comment by hyjforesight** [comment]
another issue (but I'm not sure whether it is matplotlib 3.5.1 specific): set `dyn.configuration.set_pub_style()`, tutorial can not plot figures. please check this:https://github.com/aristoteleo/dynamo-release/issues/308

**Comment by hyjforesight** [comment]
I'm not sure whether this is the compatibility issue of matplotlib, but I report it here.
Whatever the function is, `save_show_or_return='both'` or `save_show_or_return='all'` cannot save the plot. It only shows the plot.
![image](https://user-images.githubusercontent.com/75048821/176820524-6fa4e9aa-237f-4be7-b538-f1a6d517a700.png)

**Comment by elfofmaxwell** [comment]
Hello @hyjforesight, thanks a lot for summarizing the problems! For the problem about `tight_layout()`, it is solved by `matplotlib` in version 3.5.2 and please try to upgrade it. About animation, the problem would be fixed in next release very soon. For the `save_show_or_return` arg, our plot functions only accept `'save'`, `'show'`, and `'return'` as values but not `'all'` or `'both'`. For `set_pub_style()`, it seems to be a more generic problem and we are still working on it. For now please just keep using the solution you mentioned (by using `dyn.configuration.set_figure_params('dynamo', background='white')` instead).  If you have any other new problems, please just let us know!

**Comment by hyjforesight** [comment]
hello @elfofmaxwell, thanks for the response.
I think the documents for `dynamo.pl.scatters()` is wrong. It mentions `If “both”, it will save and plot the figure at the same time. If “all”, the figure will be saved, displayed and the associated axis and other object will be return` (https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.pl.scatters.html).
Is it able to make a parameter that can save and show at the same time?
Thanks!
Best,
YJ

**Comment by elfofmaxwell** [comment]
Hello @dummyindex , thank you so much for your information! We have checked our goal and confirmed that for `dynamo.pl.scatters()` there are some bugs preventing it from using `both` or `all` as values. Currently only a part of APIs of `pl` module has incomplete support for `both` and `all` values and we plan to update all other APIs in next release very soon.
