### ISSUE TITLE
Applicability of tutorials for conventional vs. time-series vs. labeling scRNA-Seq

### ISSUE THREAD

**Issue by shovikb94** [aristoteleo/dynamo-release#350]
Hello,

Thanks for creating this wonderful tool. The time you have put into documentation is really admirable. 

I noted that the tutorials are split up in some cases by the data modality (conventional vs. labeling), and in other cases by the type of analysis (differential geometry or vector field predictions). Should we assume that all analyses are applicable to all modalities if not otherwise specified? And are certain analyses optimized for certain modalities? For instance, the most probable path predictions tutorial utilizes labeling sc-RNA-seq, but I was curious if it would be applicable to conventional scRNA-Seq as well. 

Thanks again!

**Comment by Xiaojieqiu** [comment]
dear @shovikb94 thanks for your interesting in our work. 

dynamo can support both splicing based (conventional) and the labeling based data. That is, all the differential geometry analyses and vector field predictions, etc. can be used to for both data types. The only thing here is that the labeling data in general give more accurate results (splicing based analyses sometimes give inaccurate RNA velocity flow) and has real time scale (because we do know how many hours we labeled the cells). 

Hope this helps!
