### ISSUE TITLE
Perturbation with non-PCA gene?

### ISSUE THREAD

**Issue by valarauko** [aristoteleo/dynamo-release#352]
Thank you for this excellent tool!

In trying the perturbation function, I see it’s restricted to only PCA genes. Is there a way to run a perturbation workflow on genes that aren’t part of the PCA genes?

**Comment by Xiaojieqiu** [comment]
with such, then you can calculate RNA velocity, learn vector field and eventually use dynamo to predict the cell fate diversions after genetic perturbation with any genes of your interests. Hope this solves your problem!

**Comment by valarauko** [comment]
Thank you for the prompt reply! Yes, passing the list of genes of interest via the `reciple_monocle` allows me to project the perturbations for the genes. Thank you so much!

I hope it's OK for me to ask some related questions here. 

- Is there a way to quantify the level of perturbation from the WT state, ie, a metric to compare and contrast the level of disruption compared to the WT? For example, I have some related genes of interest, and at least by visual inspection of the perturbed streamline plots they look very similar though not identical. Some clusters appear unaffected while some appear to have the arrows flow in the opposite direction as the WT. It would be helpful if there were a metric to evaluate the level to which individual cell types/clusters are disrupted. Any suggestions/pointers would be helpful. Perhaps some way to compare `adata.obsm['j_delta_x_perturbation']` across different disruption experiments?
- The API documentation for the `prediction (pd)` submodule is currently inaccessible, which makes it harder to understand the format of the perturbation output.

**Comment by Xiaojieqiu** [comment]
thanks for the two additional questions. Because of my crazy time schedules, let me briefly answer you here: 
1. `adata.layers['j_delta_x_perturbation']` stores the results of the perturbation effects after the in silico perturbation for each gene in each cell. you can use this matrix for any differential analyses 
2. please use `?dyn.pd.predictions` to see the documentation. I will fix the readthedocs issue when I get some free time. you are welcoem to help on this regard too.

**Comment by Xiaojieqiu** [comment]
@valarauko the API has updated: https://dynamo-release.readthedocs.io/en/latest/API.html
