### ISSUE TITLE
Does the group parameter of tl.dynamics() correspond to the "Differential Kinetics" in scvelo?

### ISSUE THREAD

**Issue by chansigit** [aristoteleo/dynamo-release#360]
The document says that by specifying 'group' it enable estimating group-specific kinetics parameters. 

Is it an implementation similar to the scvelo "Differential Kinetics" (https://scvelo.readthedocs.io/DifferentialKinetics/)? 

If yes, should I run similar different lineage identification steps like scvelo did in the tutorial to find the different lineages (expelling the endothelial cells in their tutorials)? 

Looking forward to your answers. Thank you.

**Comment by Xiaojieqiu** [comment]
Hi @chansigit that looks like right. Yeah you should be able to identify different cell groups and then calculate the group-specific kinetics parameters. 

In addition, I wanna add that although this group argument alleviates some issues for kinetic parameters estimation and velocity calculation, some fundamental issues are still there. For the splicing data, we have to assume there are only two distinct transcription rates (one larger one for the induction phase and the another for the repression phase). This fundamental limitation (and others) makes splicing based velocity problematic sometimes. The labeling data is definitely the way to go if you may have access to it because it is automatically immune to this problem as the labeling can directly reflect the transcription rate in each cell for each gene.
