### ISSUE TITLE
Does the LAP have a scale bar?

### ISSUE THREAD

**Issue by hyjforesight** [aristoteleo/dynamo-release#383]
Hello Dynamo,
The LAP is drawn by a viridis cmap. Does it have a scale bar? Because it uses different color of viridis to show different points of the LAP, is there any meaning for the color of viridis? Does the color represent any confidence value or MSD value for the points of the LAP?
![image](https://user-images.githubusercontent.com/75048821/180567709-1cdb7c21-9c8a-4e32-a073-acf9195a2034.png)

Thanks!
Best,
YJ

**Comment by Xiaojieqiu** [comment]
the color represents the time of predicted action along the LAPs. 

see the code in the https://dynamo-release.readthedocs.io/en/latest/notebooks/lap_tutorial/lap_tutorial.html. Here the action is mapped to color. We don't have a legend for the color because each path will need to have different color legend. 

```
        for prediction, action in zip(lap_dict["prediction"], lap_dict["action"]):
            ax.scatter(*prediction[:, [x, y]].T, c=map2color(action))
            ax.plot(*prediction[:, [x, y]].T, c="k")
```

Note that you can also plot the predicted time along the least action path as the color.

**Comment by hyjforesight** [comment]
Thanks @Xiaojieqiu for the response! Appreciate it!
