### ISSUE TITLE
clustering resolution not working for Leiden and louvain

### ISSUE THREAD

**Issue by Jinerhal** [aristoteleo/dynamo-release#431]
Thank you for the great work on dynamo. About the clustering functions in dynamo (`dyn.tl.leiden`, `dyn.tl.louvain`):

1. `dyn.tl.leiden` does not accept a resolution parameter. Even this parameter is passed to `**kwargs`, cluster results will not change, since the dependency function `cdlib.algorithms.leiden` doesn't have a resolution resolution parameter too. We could really use such parameter to adjust the clustering result, like what's in `scanpy.tl.leiden`
2. `dyn.tl.louvain` does accept the resolution parameter, but there is a bug in the latest version. I get more clusters when I use smaller resolution, and larger resolution also result in more clusters, which is weird. I found out this is a `cdlib` and `python-louvain` package issue, which is still not fixed at this moment. See https://github.com/taynaud/python-louvain/issues/94, https://github.com/taynaud/python-louvain/issues/86. I tested the pervious versions of `cdlib` and `python-louvain`, and `cdlib==0.2.0` with `python-louvain==0.14` looks good to me.

So I'm sincerely asking if you could 1. add an adjustable resolution to `dyn.tl.leiden` function, and 2. look into the louvain resolution issue for a feasible solution.

**Comment by Ukyeon** [comment]
Thank you, @Jinerhal, for bringing this bug to our attention!

Firstly, we have identified that dyn.tl.leiden does not currently accept a resolution parameter, but this will be resolved in the next commit.
Secondly, we have found that previous versions of cdlib and python-louvain, cdlib==0.2.0 with python-louvain==0.14, have also worked well for us. Therefore, we encourage you to continue using those versions for [dyn.tl](http://dyn.tl/).louvain.
Please note that the resolution parameters have the same effect on both leiden and louvain function. For instance, an increase in this value will result in the generation of a greater number of clusters.

Thank you for your attention to this matter. Please let us know if you have any further questions or concerns.

**Comment by Xiaojieqiu** [comment]
Thanks @Ukyeon and @Jinerhal, based on the great from Ukyeon and me over the past a few days, we have now fully addressed these issues. Our solution can be summarized as the following: 

1. we completely replace the leiden / louvain calculation with leidenalg and louvain package so that the resolution parameter behaves as expected. 
2. because we don't use cdlib for leiden and louvain, the version issue @Jinerhal brought up is not relevant anymore. 
3. because we don't use cdlib and we replace networkx (implemented in pure python) with igraph (implemented in C) for graph construction from sparse matrix, our louvain and leiden clustering algorithms gain a significant speed boost as well. 

To demonstrate the effects of these updates, I have included the following test code and corresponding results: 
![image](https://user-images.githubusercontent.com/7456281/221027635-e7737060-c5fe-4c98-852e-6536e2aaef6f.png)

```import dynamo as dyn

adata = dyn.sample_data.hematopoiesis()

dyn.tl.louvain(adata, resolution=0.5, result_key='louvain_r0.5')
dyn.tl.louvain(adata, resolution=1, result_key='louvain_r1')
dyn.tl.louvain(adata, resolution=2, result_key='louvain_r2')

dyn.tl.leiden(adata, resolution=0.5, result_key='leiden_r0.5')
dyn.tl.leiden(adata, resolution=1, result_key='leiden_r1')
dyn.tl.leiden(adata, resolution=2, result_key='leiden_r2')

dyn.pl.umap(adata,
            color=['louvain_r0.5', 'louvain_r1', 'louvain_r2', 'leiden_r0.5', 'leiden_r1', 'leiden_r2'],
            ncols=3,
            show_legend='on data')```
