### ISSUE TITLE
quiver, streamline and fluid mechanics

### ISSUE THREAD

**Issue by wangjiawen2013** [aristoteleo/dynamo-release#449]
Hi,
In fluid mechanics, we use both flow vector and streamline to represent flow motion.  All the streamlines have the same thickness and streamline density is a measure for the magnitude of the flow velocity, the direction of flow velocity is tangential to the streamline:
![OIP-C](https://user-images.githubusercontent.com/29703450/218915563-e64f20e6-cac4-4e43-8234-b83ae875ce95.jpg)
![R-C](https://user-images.githubusercontent.com/29703450/218915567-0b17860d-b930-47c1-962f-a8bc754e2b42.png)

While dyn.pl.cell_wise_vectors and dyn.pl.streamline_plot generate quivers and streamlines with different size, which is different from that in fluid mechanics. So what's the meaning of quiver size, quiver density, quiver direction ?

And the streamlines in fluid mechanics are consecutive and will not be broken, while the streamline from dynamo are in consecutive. What's the meaning of streamline thickness, density, length ? Is the flow laminar flow or turbulent flow ?

**Comment by Xiaojieqiu** [comment]
@wangjiawen2013 great questions! I really like them. I am pleased to  discuss with a real expert in fluidic mechanics here. Yes, RNA velocity field brought the ideas of quiver and streamlines from fluidics or physics. The quiver size/density is the magnitude of the velocity from the start point.  The direction is the velocity direction from the start point. 

For the grid velocity flow and streamline, in general dynamo (and velocyto / scvelo) don't visualize the flow when the magnitude is below certain threshold. So you can see the broken flows. The thickness corresponds to the speed (magnitude) of the flow. 

We used the quiver and streamline from matplotlib to create these plots: 
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.quiver.html
https://matplotlib.org/stable/gallery/images_contours_and_fields/plot_streamplot.html

Assuming the development process is differentiable and continous, the flow can be laminar flow instead of turbulent flow. But it looks like an very interesting scientific question to study it!
