### ISSUE TITLE
Error with simplicial set embedding

### ISSUE THREAD

**Issue by rorymaizels** [aristoteleo/dynamo-release#52]
Hi,

Thanks for this great package - I understand that it is still under development so apologies if this error is something that is already known about.

I'm running dynamo version '0.0+11bf3a9' and Python 3.7.3. For a very simple test case based on sample data, I run:

```
import dynamo as dyn
adata = dyn.sample_data.BM()
dyn.pp.recipe_monocle(adata, n_top_genes=1000)

dyn.tl.dynamics(adata, filter_gene_mode="no", use_smoothed=True,
    experiment_type='conventional', assumption_mRNA='ss', model='deterministic',
    est_method='linear_regression', log_unnormalized=True)
```

The error I get is 'AttributeError: "tuple' object has no attribute 'tocoo' ". This occurs in line 201 of connectivity.py, in umap_conn_indices_dist_embedding(), when umap's simplicial_set_embedding() is called.

It appears that umap's simplicial_set_embedding() doesn't just output a scipy sparse matrix, but outputs a tuple, of which the first object is the desired matrix object (my umap version is '0.4.3').

I thought it would be worth raising this issue as it could be a simple solution, or something simple going wrong for me!

Cheers!

**Comment by Xiaojieqiu** [comment]
Hi @rorymaizels many thanks for raising this issue! Indeed it is a very simple fix. The reason is that starting from UMAP4.0, `fuzzy_simplicial_set` now returns a tuple with `result, sigmas, rhos`. I just need to take the first element when `graph` returned from `fuzzy_simplicial_set` is a tuple. 
Thanks again and please let us know any further comments / thoughts regarding our package. 

Dynamo will reach a stable version in a couple of weeks and a few notebooks/tutorials on some very exciting applications and predictions of the reconstructed vector field will be also released shortly.

**Comment by rorymaizels** [comment]
Hi Xiaojie, I thought that might be the issue! Glad to see it is an easy fix, and I look forward to exploring the stable version soon!

**Comment by Xiaojieqiu** [comment]
Hi @rorymaizels, looks like it is safe for me to close this issue now. please let me know if you run into any other issues. I am pretty responsive to fix any issues. Also comments/suggestions on making dynamo useful for your analysis are always welcome!

**Comment by Xiaojieqiu** [comment]
hey @rorymaizels, excited to let you know that dynamo now is on PyPi after almost 1200 commits. I would like to get some feedback before I advocate it in the twitter world. Please let me know if you have any further comments / suggestions. Happy to change the API or adding new supports according to your needs!
