### ISSUE TITLE
Vectorfield needs more online documentation

### ISSUE THREAD

**Issue by dummyindex** [aristoteleo/dynamo-release#73]
Thanks for making API page online.
Currently there is no online documentation about vectorfield object after running vf.VectorField, though source code comments explain this result object stored in adata well. Meanwhile, I would like to apply an existing vectorfield to some new data point to do some theoretical stuff. For now my pipeline calls vectorfield.func(X). It is handy if there is a utility function apply_vectorfield(adata_new, vectorfield) or apply_vectorfield(X, vectorfield).

Meanwhile, is topography of vectorfield only supporting 2D? If I use PCA basis, then there is some error raised.

**Comment by Xiaojieqiu** [comment]
thanks for the question! To predict on new data points, you are welcome to use the `dyn.pd.fate(adata)` function (https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.pd.fate.html#dynamo.pd.fate). let me know it goes. 

By default topography only supports 2D because calculating fixed points and characterized lines in high dimensions are not trivial. There are already some supports for fixed points in high dimensions and we will add those supports in later dynamo releases.

**Comment by dummyindex** [comment]
Cool. Thanks for your prompt reply and explanation. I will try fate function.

**Comment by stupidstupidstupidstupid** [comment]
the function's link (https://dynamo-release.readthedocs.io/en/latest/_autosummary/dynamo.pd.fate.html#dynamo.pd.fate) seems has lapsed
