### ISSUE TITLE
Add adapmap for dimensionality reduction

### ISSUE THREAD

**Issue by davisidarta** [aristoteleo/dynamo-release#82]
Hi @Xiaojieqiu ! I'm opening this issue to continue the conversation we started [here](https://twitter.com/Xiaojie_Qiu/status/1308155262180622336).

I've made some [small changes](https://github.com/davisidarta/dynamo-release/blob/master/dynamo/tools/utils_reduceDimension.py) to [utils_reduceDimension.py](https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/tools/utils_reduceDimension.py) in order to add [_adapmap_](https://github.com/davisidarta/dbMAP) as a dimensionality reduction method (a non-linear alternative to PCA, essentially consisting of adaptive multiscale diffusion maps). 

Layouts learned from this generalized diffusion structure are more informative than those learned on PCA embedding, and UMAP is particularly well-fit for embedding complex data due to a sequential approximation of the Laplace-Beltrami operator. Accordingly, dbMAP embeddings are able to visually depict cycling populations into cyclic trajectories and captures rich details from data structure into comprehensive embeddings. 

The key idea is to explore visualizations derived from non-linear diffusion structure, rather than those derived from linear projections (PCA).

I'm new to contributing within GitHub, so any help to go through the pull request would be greatly appreciated. I had issues while following the [contribution guidelines](https://github.com/aristoteleo/dynamo-release/blob/master/CONTRIBUTING.md#setting-up-a-development-environment).

**Comment by Xiaojieqiu** [comment]
Hey @davisidarta, thanks for your very speedy contribution! and congrats on the great work on ddMAP again! it is definitively an exciting advance of the current dimensional reduction method for single-cell dataset analysis (and other high-dimension data).

I went through your changes in the code and made a few quick [comments](https://github.com/davisidarta/dynamo-release/commit/0517e3a30c5c606ca1cdb9b1b62b60382b07bcf3). The contribution guideline was outdated and I really should find some time to update it (welcome your comments to make it better also!). I apologize for this inconvenience. 

In addition, I realized that we may need to update code in a few other places and do a few other things:

1. update the documentation of `reduceDimension` [function](https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/tools/dimension_reduction.py) to mention the new support of ddMap.
2. add a new plotting function `dyn.pl.ddMap`  in this [file](https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/plot/dimension_reduction.py) and include this [function](https://github.com/aristoteleo/dynamo-release/blob/master/docs/source/API.rst) in our readthedoc rst file. 
3. update setup.py file to mention ddMap as an extra dependency [here](https://github.com/aristoteleo/dynamo-release/blob/287f6443a6a524030839d7c02e1b1c791a4d93c0/setup.py#L17). We can elevate it as dependencies and put it in the **[requirements.txt](https://github.com/aristoteleo/dynamo-release/blob/master/requirements.txt)** file when things become more mature. 
4. lastly we may need to try ddMap out on a few datasets, maybe starting with the [zebrafish](https://dynamo-release.readthedocs.io/en/latest/zebrafish.html) dataset. 

Let me know whether you would like to work on those things. Otherwise, welcome to make a pull request and I will work on the merging and the things listed above. 

Thanks again!

**Comment by davisidarta** [comment]
Thank you @Xiaojieqiu ! Sorry for the minimal code, I really just wished to get a headstart. Thank you for your readiness and willingfulness to help :)

Regarding the points you mentioned:
1-2. Sure! I'll get this done tomorrow at my fork.

3. I'm rather insecurate about meddling with you guys setup.py file. Would it OK for you to do it?

4. I'm testing the embeddings on a couple of dynamo GoogleColab notebooks with some adaptations. It's a little bit harder to adapt to than scVelo, since `dyn.pp.recipe_monocle()` seems to scale the data (something we must **never** do with adapmap/dbMAP), so I'm adding a parallel minimal scanpy processing workflow for now, since I'm curious to see how results look like. Yet, this made me think we should maybe add a 5th point:

5. Change [recipes](https://github.com/aristoteleo/dynamo-release/blob/master/dynamo/preprocessing/preprocess.py) to make scaling optional (in the case users want to run adapmap / dbMAP). I'll go for it after the first notebook tests.

I'll make a PR as soon as I figure these out! I'll keep you updated :)

**Comment by Xiaojieqiu** [comment]
Thanks for your generous offer for the contribution too! Dynamo will grow stronger with the community by those contributions. (Meanwhile, we are working on a few new directions related to a more general kinetic estimation framework and better vector field reconstruction, etc.). 

Regarding to your suggestions, those all look good to me! 

3. sure, I can update our setup.py file to make dbmap as an extra dependency for now. 
4. please note that we have a few more notebooks in this [repo](https://github.com/aristoteleo/dynamo-tutorials). You can play with them if you want. 
Regarding the scaling, what do you mean by `scaling` here (is it size factor correction or log1p transformation? I believe other tools use a similar procedure also)? Here are just some details of dynamo's setup (maybe you already knew): `adata.X` is size-factor corrected and log1p transformed data. `X_spliced, X_unspliced` are size factor transformed data also (`spliced, unspliced` are raw data but you can remove them by setting `keep_raw_layers=False` in `recipe_monocle `). 
5. let me know what is the scaling here, and definitively let us make it optional if it is required for dbMAP. 

Thanks again and looking forward to your PRs!

**Comment by Xiaojieqiu** [comment]
hey @davisidarta, any progress on this? I am happy to provide any help. please also notice that our preprint is fully rewritten and can be found here: 

https://www.biorxiv.org/content/10.1101/696724v2

You can also find a 3 minute tweetorial digest here (welcome retweet): 
https://twitter.com/Xiaojie_Qiu/status/1359183325198512132

**Comment by davisidarta** [comment]
Hi @Xiaojieqiu! Thank you for the kind reminder and congratulations on your beautiful new preprint! 

I'm sorry for the huge gap - had some really tough personal obstacles since then and got my attention diverted. Thank you for offering help with the PR.

I'm updating the diffusion tools during this week and the next (getting rid of an updated dependency). I'll let you know when I get it ready and run it on some of your tutorials for comparisons by making a new comment here. 

I'd definitely appreciate help with the PR when I get that done - I'm completely on my own regarding single-cell analysis in Brazil and under a huge deal of pressure, personally and professionally, so I had to step away from development for a while and have been coming back only in the last couple weeks.

**Comment by Xiaojieqiu** [comment]
Hi @davisidarta, I am so sorry to hear that you went through some tough personal issues in the past year! I hope you and your family have got it through and wish you a great 2021! Also please let me know if I can provide any help. 

Please take your time on the PR. You are welcome to integrate it with dynamo any time you feel more convenient. 

Thanks and take care!
