### ISSUE TITLE
How to deal with the error in phase plot?

### ISSUE THREAD

**Issue by sunon77** [aristoteleo/dynamo-release#96]
When we are plotting a phage portrait, there is an error pop up. How to solve it?

![image](https://user-images.githubusercontent.com/12102715/95529173-3d262d80-09a8-11eb-8c05-87ee249ccec5.png)

**Comment by Xiaojieqiu** [comment]
Thanks for your question! Your description of the issue is not clear. I would really appreciate a more specific description (and reproducible code). Also, based on the screenshot, it looks like a general python issue but not specific to dynamo. The error basically indicates the `gamma, velocity_offset` is not numeric values in your case so `np.isfinite ` is not applicable. 

Please note that you need to use the help function `dyn.convert2float(adata, ["gamma", "gamma_b"], var=True)` to convert the `gamma, gamma_b` columns in **.var**  back to numeric values if you reloaded your adata object from a saved .h5ad file.
